// Generated by CoffeeScript 1.10.0

/*
Created by Robsdedude on 01/10/2017
Virtual gamepad application
 */

(function() {
  var earlyDeathCount, exiting, forever, i, len, log, ref, server, sig;

  forever = require("forever-monitor");

  log = require("./lib/log");

  var options = {
    max: Infinity,
    args: ["--https", "--key", "key.pem", "--cert", "cert.pem"],
  };

  if (process.env.HOT_RELOAD) {
    options.watch = true;
    options.watchDirectory = __dirname;
    options.watchIgnorePatterns = ["presets/**", "node_modules/**", ".git/**"];
    log("info", "Hot reload is ENABLED (watching for file changes)");
  }

  var child_process = require("child_process");

  function autoHealSystem() {
    log("warning", "[AUTO-HEAL] Executing system self-recovery routine...");
    try {
      // 1. Ensure uinput kernel module is loaded
      child_process.execSync("modprobe uinput 2>/dev/null || true");
      log("info", "[AUTO-HEAL] Verified uinput kernel module");
    } catch(e) {}

    try {
      // 2. Fix /dev/uinput permissions if restricted
      child_process.execSync("chmod 666 /dev/uinput 2>/dev/null || true");
    } catch(e) {}

    try {
      // 3. Clear any zero-byte or corrupted SSL certs
      var sslDir = require("path").join(__dirname, "ssl");
      ["key.pem", "cert.pem"].forEach(function(f) {
        var p = require("path").join(sslDir, f);
        if (require("fs").existsSync(p) && require("fs").statSync(p).size === 0) {
          require("fs").unlinkSync(p);
          log("info", "[AUTO-HEAL] Cleared corrupted 0-byte cert file: " + f);
        }
      });
    } catch(e) {}

    try {
      // 4. Force release stuck network ports
      [8443, 8080, 8000, 3000, 8081].forEach(function(p) {
        child_process.execSync("fuser -k -s " + p + "/tcp 2>/dev/null || true");
      });
      log("info", "[AUTO-HEAL] Released stuck network ports (8443, 8080, 8000, 3000, 8081)");
    } catch(e) {}
  }

  server = new forever.Monitor(
    require("path").resolve(__dirname, "server.js"),
    options
  );

  exiting = false;

  server.on("exit", function() {
    return log("warning", "server.js has exited");
  });

  earlyDeathCount = 0;

  server.on("exit:code", function() {
    var diedAfter;
    if (exiting) {
      return;
    }
    diedAfter = Date.now() - server.ctime;
    log("info", "diedAfter: " + diedAfter);
    earlyDeathCount = diedAfter < 5000 ? earlyDeathCount + 1 : 0;
    log("info", "earlyDeathCount: " + earlyDeathCount);
    if (earlyDeathCount >= 3) {
      log("warning", "[AUTO-HEAL] Crash loop detected. Triggering auto-heal recovery...");
      autoHealSystem();
      earlyDeathCount = 0;
      return;
    }
  });

  server.on("restart", function() {
    return log(
      "error",
      "Forever restarting script for " + server.times + " time",
    );
  });

  ref = ["SIGTERM", "SIGINT", "exit"];
  for (i = 0, len = ref.length; i < len; i++) {
    sig = ref[i];
    process.on(
      sig,
      (function(s) {
        return function() {
          log("info", "received " + s);
          exiting = true;
          try {
            if (server.running) {
              server.stop();
            }
          } catch (e) {
            log("error", e.message);
          }
          if (s !== "exit") {
            return process.exit(0);
          }
        };
      })(sig),
    );
  }

  server.start();
}).call(this);
