// Generated by CoffeeScript 1.10.0

/*
Created by MIROOF on 04/03/2015
Virtual gamepad application
 */

// ========== NODE PROCESS-LEVEL DIAGNOSTICS (runs before everything) ==========
(function() {
  // Early console log before winston loads, in case winston itself crashes
  var _startTime = Date.now();
  console.log('[NODE] ============================================');
  console.log('[NODE] Process starting at ' + new Date().toISOString());
  console.log('[NODE] Node.js version: ' + process.version);
  console.log('[NODE] Platform: ' + process.platform + ' | Arch: ' + process.arch);
  console.log('[NODE] PID: ' + process.pid + ' | PPID: ' + process.ppid);
  console.log('[NODE] User: ' + (process.env.USER || process.env.USERNAME || 'unknown') + ' | UID: ' + (process.getuid ? process.getuid() : 'N/A') + ' | GID: ' + (process.getgid ? process.getgid() : 'N/A'));
  console.log('[NODE] CWD: ' + process.cwd());
  console.log('[NODE] __dirname: ' + __dirname);
  console.log('[NODE] argv: ' + JSON.stringify(process.argv));
  console.log('[NODE] env.PORT: ' + (process.env.PORT || 'not set'));
  console.log('[NODE] env.LOGLEVEL: ' + (process.env.LOGLEVEL || 'not set'));
  console.log('[NODE] env.HOT_RELOAD: ' + (process.env.HOT_RELOAD || 'not set'));
  var mem = process.memoryUsage();
  console.log('[NODE] Memory: RSS=' + Math.round(mem.rss/1024/1024) + 'MB | Heap=' + Math.round(mem.heapUsed/1024/1024) + '/' + Math.round(mem.heapTotal/1024/1024) + 'MB');
  console.log('[NODE] ============================================');

  // Catch EVERYTHING at the Node level
  process.on('warning', function(warning) {
    console.log('[NODE] WARNING: ' + warning.name + ': ' + warning.message);
    if (warning.stack) console.log('[NODE] Stack: ' + warning.stack);
  });

  process.on('uncaughtException', function(err) {
    console.log('[NODE] UNCAUGHT EXCEPTION: ' + err.message);
    console.log('[NODE] Stack: ' + err.stack);
    // Don't exit — let the process supervisor handle it, but log it
  });

  process.on('unhandledRejection', function(reason, promise) {
    console.log('[NODE] UNHANDLED REJECTION: ' + reason);
  });

  process.on('exit', function(code) {
    var uptime = ((Date.now() - _startTime) / 1000).toFixed(1);
    console.log('[NODE] Process exiting with code ' + code + ' after ' + uptime + 's uptime');
  });

  ['SIGTERM', 'SIGINT', 'SIGHUP'].forEach(function(sig) {
    process.on(sig, function() {
      console.log('[NODE] Received signal: ' + sig);
      if (typeof gracefulShutdown === 'function') {
        gracefulShutdown(sig);
      }
    });
  });
  // ========== END NODE DIAGNOSTICS ==========

  var app, config, express, gamepad_hub, gp_hub, https, fs, server, io, kb_hub, keyboard_hub, log, path, port, suffix, touchpad_hub, tp_hub;

  path = require('path');
  express = require('express');
  app = express();
  https = require('https');
  fs = require('fs');
  console.log('[NODE] Core modules loaded (path, express, https, fs)');

  // Read settings and required modules
  config = require('./config.json');
  console.log('[NODE] Config loaded: ' + JSON.stringify(config));
  log = require('./lib/log');
  console.log('[NODE] Logger loaded');

  // SSL settings for HTTPS server
  var sslDir = path.join(__dirname, 'ssl');
  var keyPath = path.join(sslDir, 'key.pem');
  var certPath = path.join(sslDir, 'cert.pem');

  function ensureCerts() {
    if (!fs.existsSync(sslDir)) {
      fs.mkdirSync(sslDir, { recursive: true });
    }
    if (fs.existsSync(keyPath) && fs.existsSync(certPath)) {
      try {
        fs.accessSync(keyPath, fs.constants.R_OK);
        fs.accessSync(certPath, fs.constants.R_OK);
      } catch (permErr) {
        log('warning', '[AUTO-HEAL] SSL certificate permission error (EACCES). Fixing file permissions...');
        try {
          var _cp = require('child_process');
          _cp.execSync('chmod 666 "' + keyPath + '" "' + certPath + '" 2>/dev/null || true');
          _cp.execSync('chmod 777 "' + sslDir + '" 2>/dev/null || true');
        } catch(e) {}
      }
    }

    if (!fs.existsSync(keyPath) || !fs.existsSync(certPath)) {
      log('info', 'Generating self-signed SSL certificate with SAN...');
      var child_process = require('child_process');
      var os = require('os');

      // Collect all local IP addresses for SAN entries
      var sanEntries = ['DNS:localhost', 'IP:127.0.0.1', 'IP:::1'];
      var interfaces = os.networkInterfaces();
      Object.keys(interfaces).forEach(function(ifname) {
        interfaces[ifname].forEach(function(iface) {
          if (!iface.internal && iface.family === 'IPv4') {
            sanEntries.push('IP:' + iface.address);
          }
        });
      });
      var sanString = sanEntries.join(',');
      log('info', 'Certificate SANs: ' + sanString);

      try {
        child_process.execSync(
          'openssl req -x509 -newkey rsa:2048 -keyout "' + keyPath + '" -out "' + certPath + '" -days 3650 -nodes ' +
          '-subj "/C=US/ST=State/L=Locality/O=VirtualGamepads/CN=localhost" ' +
          '-addext "subjectAltName=' + sanString + '"',
          { stdio: 'ignore' }
        );
        child_process.execSync('chmod 666 "' + keyPath + '" "' + certPath + '" 2>/dev/null || true');
        log('info', 'SSL certificate generated at ' + sslDir);
      } catch (err) {
        log('error', 'Failed to generate SSL certificate: ' + err.message);
        throw err;
      }
    }
  }

  ensureCerts();
  log('debug', '[INIT] SSL certs verified at ' + sslDir);

  var keyData, certData;
  try {
    keyData = fs.readFileSync(keyPath);
    certData = fs.readFileSync(certPath);
  } catch (readErr) {
    log('warning', '[AUTO-HEAL] Reading SSL cert failed (' + readErr.message + '). Regenerating certs...');
    try {
      if (fs.existsSync(keyPath)) fs.unlinkSync(keyPath);
      if (fs.existsSync(certPath)) fs.unlinkSync(certPath);
    } catch(e) {}
    ensureCerts();
    keyData = fs.readFileSync(keyPath);
    certData = fs.readFileSync(certPath);
  }

  var options = {
    key: keyData,
    cert: certData,
  };
  log('debug', '[INIT] SSL key size: ' + options.key.length + ' bytes, cert size: ' + options.cert.length + ' bytes');

  // Dump certificate SAN info for verification
  try {
    var _cp = require('child_process');
    var _sanInfo = _cp.execSync('openssl x509 -in "' + certPath + '" -noout -ext subjectAltName 2>/dev/null', { encoding: 'utf8' }).trim();
    log('debug', '[INIT] Certificate SAN: ' + _sanInfo);
  } catch(e) { log('debug', '[INIT] Could not read SAN from cert'); }

  // Create HTTPS server
  server = https.createServer(options, app);

  // ========== DEEP CONNECTION DEBUG LOGGING ==========
  // Log raw TCP connections (before TLS handshake)
  server.on('connection', function(socket) {
    var remote = socket.remoteAddress + ':' + socket.remotePort;
    log('debug', '[TCP] New connection from ' + remote);
    socket.on('error', function(err) {
      log('debug', '[TCP] Socket error from ' + remote + ': ' + err.message);
    });
    socket.on('close', function(hadError) {
      log('debug', '[TCP] Connection closed from ' + remote + (hadError ? ' (with error)' : ''));
    });
  });

  // Log successful TLS handshakes
  server.on('secureConnection', function(tlsSocket) {
    var remote = tlsSocket.remoteAddress + ':' + tlsSocket.remotePort;
    var proto = tlsSocket.getProtocol ? tlsSocket.getProtocol() : 'unknown';
    var cipher = tlsSocket.getCipher ? JSON.stringify(tlsSocket.getCipher()) : 'unknown';
    log('debug', '[TLS] Handshake SUCCESS from ' + remote + ' | protocol=' + proto + ' cipher=' + cipher);
  });

  // Log TLS handshake failures (demote self-signed cert probe alerts to debug level)
  server.on('tlsClientError', function(err, tlsSocket) {
    var remote = tlsSocket.remoteAddress ? (tlsSocket.remoteAddress + ':' + tlsSocket.remotePort) : 'unknown';
    var isCertUnknown = err.message && (err.message.indexOf('certificate unknown') !== -1 || err.message.indexOf('alert number 46') !== -1 || err.code === 'ERR_SSL_SSLV3_ALERT_CERTIFICATE_UNKNOWN');
    var level = isCertUnknown ? 'debug' : 'warning';
    log(level, '[TLS] Handshake notice from ' + remote + ': ' + err.message);
    log('debug', '[TLS] Error code: ' + err.code);
  });

  // Log HTTP-level client errors
  server.on('clientError', function(err, socket) {
    var remote = socket.remoteAddress ? (socket.remoteAddress + ':' + socket.remotePort) : 'unknown';
    var isCertUnknown = err.message && (err.message.indexOf('certificate unknown') !== -1 || err.message.indexOf('alert number 46') !== -1);
    var level = isCertUnknown ? 'debug' : 'warning';
    log(level, '[HTTP] Client notice from ' + remote + ': ' + err.message);
  });

  // Catch uncaught exceptions to prevent silent crashes
  process.on('uncaughtException', function(err) {
    log('error', '[CRASH] Uncaught exception: ' + err.message);
    log('error', '[CRASH] Stack: ' + err.stack);
  });

  process.on('unhandledRejection', function(reason) {
    log('error', '[CRASH] Unhandled rejection: ' + reason);
  });
  // ========== END DEBUG LOGGING ==========

  // Connect Socket.IO to HTTPS server
  io = require('socket.io')(server);

  // Load controller-related modules
  log('debug', '[INIT] Loading controller hubs...');
  gamepad_hub = require('./app/virtual_gamepad_hub');
  gp_hub = new gamepad_hub();
  log('debug', '[INIT] ✓ Gamepad hub loaded');

  keyboard_hub = require('./app/virtual_keyboard_hub');
  kb_hub = new keyboard_hub();
  log('debug', '[INIT] ✓ Keyboard hub loaded');

  touchpad_hub = require('./app/virtual_touchpad_hub');
  tp_hub = new touchpad_hub();
  log('debug', '[INIT] ✓ Touchpad hub loaded');

  var xinput_gamepad_hub = require('./app/virtual_xinput_gamepad_hub');
  var xgp_hub = new xinput_gamepad_hub();
  log('debug', '[INIT] ✓ XInput gamepad hub loaded');
  
  var xboxone_gamepad_hub = require('./app/virtual_xboxone_hub');
  var xboxone_hub = new xboxone_gamepad_hub();
  log('debug', '[INIT] ✓ Xbox One hub loaded');

  var virtual_wheel_hub = require('./app/virtual_wheel_hub');
  var wh_hub = new virtual_wheel_hub();
  log('debug', '[INIT] ✓ Wheel hub loaded');
  log('debug', '[INIT] All controller hubs loaded successfully');

// Port configuration - parse custom port from --port flag, process.env.PORT, or config.json
var customPort = process.env.PORT;
for (var i = 0; i < process.argv.length; i++) {
  var arg = process.argv[i];
  if (arg.indexOf('--port=') === 0) {
    customPort = arg.split('=')[1].replace(/"/g, '');
  } else if ((arg === '--port' || arg === '-p') && process.argv[i + 1]) {
    customPort = process.argv[i + 1].replace(/"/g, '');
  }
}

var primaryPort = customPort ? parseInt(customPort, 10) : (process.env.PORT ? parseInt(process.env.PORT, 10) : config.port);

if (isNaN(primaryPort) || primaryPort < 1 || primaryPort > 65535) {
  if (customPort === '80085' || primaryPort === 80085) {
    log('warning', 'Port 80085 exceeds maximum TCP port (65535). Automatically correcting to port 8085...');
    primaryPort = 8085;
  } else {
    log('warning', 'Port ' + primaryPort + ' is out of valid TCP range (1 - 65535). Falling back to config port ' + config.port);
    primaryPort = config.port;
  }
}

var fallbackPorts = config.fallbackPorts || [8080, 8000, 3000, 8081];
var allPorts = [primaryPort].concat(fallbackPorts);
var maxTries = config.maxPortTries || 5;

// Determine URL suffix based on control type
if (config.analog) {
 suffix = '?analog';
} else {
 suffix = '';
}

  // Redirect to main page
  app.get('/', function(req, res) {
    if (config.useGamepadByDefault) {
      return res.redirect('gamepad.html' + suffix);
    } else {
      return res.redirect('index.html' + suffix);
    }
  });

  // Request logging middleware (logs every HTTP request that makes it through TLS)
  app.use(function(req, res, next) {
    log('debug', '[HTTP] ' + req.method + ' ' + req.url + ' from ' + req.ip);
    next();
  });

  // Serve static files
  app.use(express.json());
  app.use(express["static"](__dirname + '/public'));

  // REST API for Wheel Presets
  var presetsDir = path.join(__dirname, 'presets', 'wheel');
  
  app.get('/api/wheel-presets', function(req, res) {
    fs.readdir(presetsDir, function(err, files) {
      if (err) return res.json([]);
      var presets = files.filter(f => f.endsWith('.json')).map(f => f.replace('.json', ''));
      res.json(presets);
    });
  });

  app.get('/api/wheel-presets/:name', function(req, res) {
    var p = path.join(presetsDir, req.params.name + '.json');
    fs.readFile(p, 'utf8', function(err, data) {
      if (err) return res.status(404).json({error: 'Not found'});
      try { res.json(JSON.parse(data)); }
      catch(e) { res.status(500).json({error: 'Invalid JSON'}); }
    });
  });

  app.post('/api/wheel-presets', function(req, res) {
    var name = req.body.name;
    var configData = req.body.config;
    if (!name || !configData) return res.status(400).json({error: 'Missing name or config'});
    var p = path.join(presetsDir, name + '.json');
    fs.writeFile(p, JSON.stringify(configData, null, 2), function(err) {
      if (err) return res.status(500).json({error: 'Failed to save'});
      res.json({success: true});
    });
  });

  app.delete('/api/wheel-presets/:name', function(req, res) {
    var p = path.join(presetsDir, req.params.name + '.json');
    fs.unlink(p, function(err) {
      if (err) return res.status(500).json({error: 'Failed to delete'});
      res.json({success: true});
    });
  });

  // GET /api/button-icons — list available SVG icon names (without extension)
  app.get('/api/button-icons', function(req, res) {
    var iconsDir = path.join(__dirname, 'public', 'images', 'icons', 'buttons');
    fs.readdir(iconsDir, function(err, files) {
      if (err) return res.json([]);
      var icons = files
        .filter(function(f) { return f.endsWith('.svg'); })
        .map(function(f) { return f.replace('.svg', ''); });
      res.json(icons);
    });
  });

  // Device connection tracking for auto-kick oldest
  var deviceConnections = {
    gamepad: {},
    xinputGamepad: {},
    xboxOneGamepad: {},
    wheel: {},
    keyboard: {},
    touchpad: {}
  };

  // Find and kick the oldest device of a given type, then call onFreed callback
  function kickOldestDevice(deviceType, hub, disconnectFn, idArrayName, onFreed) {
    var oldest = null;
    var oldestId = null;
    for (var slotId in deviceConnections[deviceType]) {
      var entry = deviceConnections[deviceType][slotId];
      if (!oldest || entry.connectedAt < oldest.connectedAt) {
        oldest = entry;
        oldestId = parseInt(slotId);
      }
    }
    if (oldest && oldestId !== null) {
      log('info', 'Max ' + deviceType + ' capacity reached. Kicking device on slot ' + oldestId);
      // Remove from the old socket's tracking array
      var oldSocket = oldest.socket;
      if (oldSocket && oldSocket[idArrayName]) {
        var idx = oldSocket[idArrayName].indexOf(oldestId);
        if (idx >= 0) oldSocket[idArrayName].splice(idx, 1);
      }
      delete deviceConnections[deviceType][oldestId];
      // Disconnect from hub
      hub[disconnectFn](oldestId, function() {
        log('info', 'Kicked ' + deviceType + ' slot ' + oldestId + ' successfully freed.');
        onFreed();
      });
    } else {
      log('warning', 'Could not find any ' + deviceType + ' to kick.');
    }
  }

  // Socket.IO connection management
  io.on('connection', function(socket) {
    // Initialize arrays for multi-controller tracking per socket
    socket.gamePadIds = [];
    socket.xinputGamePadIds = [];
    socket.xboxOneGamePadIds = [];
    socket.wheelIds = [];
    socket.keyBoardIds = [];
    socket.touchpadIds = [];

    socket.on('disconnect', function() {
      // Disconnect all gamepads owned by this socket
      socket.gamePadIds.forEach(function(padId) {
        log('info', ' Gamepad ' + padId + ' disconnected');
        delete deviceConnections.gamepad[padId];
        gp_hub.disconnectGamepad(padId, function() {});
      });

      // Disconnect all xinput gamepads owned by this socket
      socket.xinputGamePadIds.forEach(function(padId) {
        delete deviceConnections.xinputGamepad[padId];
        xgp_hub.disconnectGamepad(padId, function() {
          log('info', 'Xinput gamepad ' + padId + ' disconnected.');
        });
      });
      // Disconnect all xboxone gamepads owned by this socket
      socket.xboxOneGamePadIds.forEach(function(padId) {
        delete deviceConnections.xboxOneGamepad[padId];
        xboxone_hub.disconnectGamepad(padId, function() {
          log('info', 'Xboxone gamepad ' + padId + ' disconnected.');
        });
      });

      // Disconnect all wheels owned by this socket
      socket.wheelIds.forEach(function(padId) {
        delete deviceConnections.wheel[padId];
        wh_hub.disconnectWheel(padId, function() {
          log('info', 'Virtual wheel ' + padId + ' disconnected.');
        });
      });

      // Disconnect all keyboards owned by this socket
      socket.keyBoardIds.forEach(function(boardId) {
        log('info', ' Keyboard ' + boardId + ' disconnected');
        delete deviceConnections.keyboard[boardId];
        kb_hub.disconnectKeyboard(boardId, function() {});
      });

      // Disconnect all touchpads owned by this socket
      socket.touchpadIds.forEach(function(touchpadId) {
        log('info', ' Touchpad ' + touchpadId + ' disconnected');
        delete deviceConnections.touchpad[touchpadId];
        tp_hub.disconnectTouchpad(touchpadId, function() {});
      });

      if (socket.gamePadIds.length === 0 &&
          socket.xinputGamePadIds.length === 0 &&
          socket.xboxOneGamePadIds.length === 0 &&
          socket.wheelIds.length === 0 &&
          socket.keyBoardIds.length === 0 &&
          socket.touchpadIds.length === 0) {
        log('info', ' Unknown disconnect');
      }
    });

    // Manage Gamepad connection
    socket.on('connectGamepad', function() {
      function tryConnectGamepad() {
        gp_hub.connectGamepad(function(gamePadId) {
          var ledBitField;
          ledBitField = config.ledBitFieldSequence[gamePadId];
          if (gamePadId !== -1) {
            log('info', ' connectGamepad: success (slot ' + gamePadId + ')');
            socket.gamePadIds.push(gamePadId);
            deviceConnections.gamepad[gamePadId] = { socket: socket, connectedAt: Date.now() };
            return socket.emit('gamepadConnected', {
              padId: gamePadId,
              ledBitField: ledBitField
            });
          } else {
            // Auto-kick oldest gamepad and retry
            kickOldestDevice('gamepad', gp_hub, 'disconnectGamepad', 'gamePadIds', tryConnectGamepad);
          }
        });
      }
      tryConnectGamepad();
    });

    // Manage Gamepad events — routes by padId in data (with backward compat)
    socket.on('padEvent', function(data) {
      log('debug', 'padEvent ' + JSON.stringify(data));
      if (!data) return;
      // Backward compat: old clients don't send padId, use first connected pad
      var targetPadId = (data.padId !== undefined) ? data.padId : socket.gamePadIds[0];
      if (targetPadId !== undefined && socket.gamePadIds.indexOf(targetPadId) !== -1) {
        return gp_hub.sendEvent(targetPadId, data);
      }
    });

    // Manage XInput Gamepad connection
    socket.on('connectXInputGamepad', function() {
      function tryConnectXInput() {
        xgp_hub.connectGamepad(function(gamePadId) {
          var ledBitField;
          ledBitField = config.ledBitFieldSequence[gamePadId];
          if (gamePadId !== -1) {
            log('info', ' connectXInputGamepad: success (slot ' + gamePadId + ')');
            socket.xinputGamePadIds.push(gamePadId);
            deviceConnections.xinputGamepad[gamePadId] = { socket: socket, connectedAt: Date.now() };
            return socket.emit('xinputGamepadConnected', {
              padId: gamePadId,
              ledBitField: ledBitField
            });
          } else {
            kickOldestDevice('xinputGamepad', xgp_hub, 'disconnectGamepad', 'xinputGamePadIds', tryConnectXInput);
          }
        });
      }
      tryConnectXInput();
    });

    // Manage XInput Gamepad events — now routes by padId in data
    socket.on('xinputPadEvent', function(data) {
      log('debug', 'xinputPadEvent ' + JSON.stringify(data));
      if (data && data.padId !== undefined && socket.xinputGamePadIds.indexOf(data.padId) !== -1) {
        xgp_hub.sendEvent(data.padId, data);
      }
    });

    socket.on('connectXboxOneGamepad', function() {
      var vibrateCallback = function(gamePadId, duration) {
        if (socket.xboxOneGamePadIds.indexOf(gamePadId) !== -1) {
          socket.emit('xboxOneVibrate', { duration: duration });
        }
      };
      function tryConnectXboxOne() {
        xboxone_hub.connectGamepad(function(gamePadId) {
          if (gamePadId !== -1) {
            socket.xboxOneGamePadIds.push(gamePadId);
            deviceConnections.xboxOneGamepad[gamePadId] = { socket: socket, connectedAt: Date.now() };
            return socket.emit('xboxOneGamepadConnected', {
              padId: gamePadId
            });
          } else {
            kickOldestDevice('xboxOneGamepad', xboxone_hub, 'disconnectGamepad', 'xboxOneGamePadIds', tryConnectXboxOne);
          }
        }, vibrateCallback);
      }
      tryConnectXboxOne();
    });

    socket.on('xboxOnePadEvent', function(data) {
      log('debug', 'xboxOnePadEvent ' + JSON.stringify(data));
      if (data && data.padId !== undefined && socket.xboxOneGamePadIds.indexOf(data.padId) !== -1) {
        xboxone_hub.sendEvent(data.padId, data);
      }
    });

    // Manage Wheel connection
    socket.on('connectWheel', function() {
      function tryConnectWheel() {
        wh_hub.connectWheel(function(gamePadId) {
          var ledBitField = config.ledBitFieldSequence[gamePadId];
          if (gamePadId !== -1) {
            log('info', ' connectWheel: success (slot ' + gamePadId + ')');
            socket.wheelIds.push(gamePadId);
            deviceConnections.wheel[gamePadId] = { socket: socket, connectedAt: Date.now() };
            return socket.emit('wheelConnected', { padId: gamePadId, ledBitField: ledBitField, hasClutch: true });
          } else {
            kickOldestDevice('wheel', wh_hub, 'disconnectWheel', 'wheelIds', tryConnectWheel);
          }
        });
      }
      tryConnectWheel();
    });

    // Manage Wheel events
    socket.on('wheelEvent', function(data) {
      if (data && typeof data === 'object') {
        log('debug', 'wheelEvent ' + JSON.stringify(data));
        if (data.padId !== undefined && socket.wheelIds.indexOf(data.padId) !== -1) {
          try {
            wh_hub.sendEvent(data.padId, data);
          } catch(err) {
            log('warning', '[SAFEGUARD] Error sending wheel event: ' + err.message);
          }
        }
      }
    });

    // Manage Keyboard connection
    socket.on('connectKeyboard', function() {
      function tryConnectKeyboard() {
        kb_hub.connectKeyboard(function(keyBoardId) {
          if (keyBoardId !== -1) {
            log('info', ' connectKeyboard: success (slot ' + keyBoardId + ')');
            socket.keyBoardIds.push(keyBoardId);
            deviceConnections.keyboard[keyBoardId] = { socket: socket, connectedAt: Date.now() };
            return socket.emit('keyboardConnected', {
              boardId: keyBoardId
            });
          } else {
            kickOldestDevice('keyboard', kb_hub, 'disconnectKeyboard', 'keyBoardIds', tryConnectKeyboard);
          }
        });
      }
      tryConnectKeyboard();
    });

    // Manage Keyboard events (with backward compat)
    socket.on('boardEvent', function(data) {
      log('debug', 'boardEvent ' + JSON.stringify(data));
      if (!data) return;
      var targetBoardId = (data.boardId !== undefined) ? data.boardId : socket.keyBoardIds[0];
      if (targetBoardId !== undefined && socket.keyBoardIds.indexOf(targetBoardId) !== -1) {
        return kb_hub.sendEvent(targetBoardId, data);
      }
    });

    // Manage Touchpad connection
    socket.on('connectTouchpad', function() {
      function tryConnectTouchpad() {
        tp_hub.connectTouchpad(function(touchpadId) {
          if (touchpadId !== -1) {
            log('info', ' connectTouchpad: success (slot ' + touchpadId + ')');
            socket.touchpadIds.push(touchpadId);
            deviceConnections.touchpad[touchpadId] = { socket: socket, connectedAt: Date.now() };
            return socket.emit('touchpadConnected', {
              touchpadId: touchpadId
            });
          } else {
            kickOldestDevice('touchpad', tp_hub, 'disconnectTouchpad', 'touchpadIds', tryConnectTouchpad);
          }
        });
      }
      tryConnectTouchpad();
    });

    // Manage Touchpad events (with backward compat)
    socket.on('touchpadEvent', function(data) {
      log('debug', 'touchpadEvent ' + JSON.stringify(data));
      if (!data) return;
      var targetTouchpadId = (data.touchpadId !== undefined) ? data.touchpadId : socket.touchpadIds[0];
      if (targetTouchpadId !== undefined && socket.touchpadIds.indexOf(targetTouchpadId) !== -1) {
        return tp_hub.sendEvent(targetTouchpadId, data);
      }
    });

    // Controller status endpoint — returns slot occupancy for all controller types
    socket.on('getControllerStatus', function() {
      return socket.emit('controllerStatus', {
        gamepads: gp_hub.getStatus(),
        xinputGamepads: xgp_hub.getStatus(),
        xboxOneGamepads: xboxone_hub.getStatus(),
        wheels: wh_hub.getStatus(),
        keyboards: kb_hub.getStatus(),
        touchpads: tp_hub.getStatus()
      });
    });

    // Disconnect a specific controller by type and padId
    socket.on('disconnectController', function(data) {
      if (!data || data.padId === undefined || !data.type) return;
      var padId = data.padId;
      var idx;

      switch (data.type) {
        case 'gamepad':
          idx = socket.gamePadIds.indexOf(padId);
          if (idx !== -1) {
            socket.gamePadIds.splice(idx, 1);
            delete deviceConnections.gamepad[padId];
            gp_hub.disconnectGamepad(padId, function() {
              log('info', ' Gamepad ' + padId + ' manually disconnected');
              socket.emit('controllerDisconnected', { type: 'gamepad', padId: padId });
            });
          }
          break;
        case 'xinputGamepad':
          idx = socket.xinputGamePadIds.indexOf(padId);
          if (idx !== -1) {
            socket.xinputGamePadIds.splice(idx, 1);
            delete deviceConnections.xinputGamepad[padId];
            xgp_hub.disconnectGamepad(padId, function() {
              log('info', 'Xinput gamepad ' + padId + ' manually disconnected');
              socket.emit('controllerDisconnected', { type: 'xinputGamepad', padId: padId });
            });
          }
          break;
        case 'xboxOneGamepad':
          idx = socket.xboxOneGamePadIds.indexOf(padId);
          if (idx !== -1) {
            socket.xboxOneGamePadIds.splice(idx, 1);
            delete deviceConnections.xboxOneGamepad[padId];
            xboxone_hub.disconnectGamepad(padId, function() {
              log('info', 'Xboxone gamepad ' + padId + ' manually disconnected');
              socket.emit('controllerDisconnected', { type: 'xboxOneGamepad', padId: padId });
            });
          }
          break;
        case 'wheel':
          idx = socket.wheelIds.indexOf(padId);
          if (idx !== -1) {
            socket.wheelIds.splice(idx, 1);
            delete deviceConnections.wheel[padId];
            wh_hub.disconnectWheel(padId, function() {
              log('info', 'Virtual wheel ' + padId + ' manually disconnected');
              socket.emit('controllerDisconnected', { type: 'wheel', padId: padId });
            });
          }
          break;
        case 'keyboard':
          idx = socket.keyBoardIds.indexOf(padId);
          if (idx !== -1) {
            socket.keyBoardIds.splice(idx, 1);
            delete deviceConnections.keyboard[padId];
            kb_hub.disconnectKeyboard(padId, function() {
              log('info', ' Keyboard ' + padId + ' manually disconnected');
              socket.emit('controllerDisconnected', { type: 'keyboard', padId: padId });
            });
          }
          break;
        case 'touchpad':
          idx = socket.touchpadIds.indexOf(padId);
          if (idx !== -1) {
            socket.touchpadIds.splice(idx, 1);
            delete deviceConnections.touchpad[padId];
            tp_hub.disconnectTouchpad(padId, function() {
              log('info', ' Touchpad ' + padId + ' manually disconnected');
              socket.emit('controllerDisconnected', { type: 'touchpad', padId: padId });
            });
          }
          break;
      }
    });
  });

var activeRedirectServer = null;

// Function to start HTTP -> HTTPS redirect server after main HTTPS server is listening
var startHttpRedirectServer = function(httpsPort) {
  var http = require('http');
  var httpPort = 80;
  
  var redirectApp = http.createServer(function(req, res) {
    var host = req.headers.host || '';
    var hostname = host.replace(/:\d+$/, '');
    var httpsUrl = 'https://' + hostname + ':' + httpsPort + req.url;
    log('info', '[HTTP→HTTPS] Redirecting ' + req.socket.remoteAddress + ' from http://' + host + req.url + ' → ' + httpsUrl);
    res.writeHead(301, { 'Location': httpsUrl });
    res.end('Redirecting to ' + httpsUrl);
  });
  activeRedirectServer = redirectApp;

  redirectApp.on('error', function(err) {
    if (err.code === 'EACCES' || err.code === 'EADDRINUSE') {
      if (httpPort === 80) {
        // Try fallback HTTP port 8008 (avoiding 8080 which might be used by main HTTPS server)
        httpPort = 8008;
        if (httpPort !== httpsPort) {
          log('info', '[HTTP→HTTPS] Port 80 unavailable, trying fallback port 8008 for HTTP redirect...');
          try { redirectApp.listen(8008, '0.0.0.0'); } catch(e) {}
        }
      } else {
        log('info', '[HTTP→HTTPS] Could not start HTTP redirect server. Users must type https:// manually.');
      }
    }
  });

  redirectApp.on('listening', function() {
    log('info', '[HTTP→HTTPS] Redirect server active on port ' + httpPort + ' -> https://:' + httpsPort);
  });

  try {
    redirectApp.listen(80, '0.0.0.0');
  } catch(e) {}
};

// Try ports sequentially for main HTTPS server with EADDRINUSE retry backoff
var tryPort = function(ports, index, retries) {
  if (retries === undefined) retries = 0;
  var maxRetriesPerPort = 3;

  if (index >= ports.length || index >= maxTries) {
    log('error', 'No available ports found after ' + maxTries + ' attempts');
    process.exit(1);
  }

  var attemptPort = ports[index];
  var listenServer;

  if (index === 0 && retries === 0) {
    listenServer = server;
  } else {
    listenServer = https.createServer(options, app);
    io.attach(listenServer);
  }

  var errorHandler = function(err) {
    listenServer.removeListener('listening', listeningHandler);
    try { listenServer.close(); } catch(e) {}

    if (err.code === 'EADDRINUSE' && retries < maxRetriesPerPort) {
      log('info', 'Port ' + attemptPort + ' busy (EADDRINUSE), retrying in 300ms (' + (retries + 1) + '/' + maxRetriesPerPort + ')...');
      setTimeout(function() {
        tryPort(ports, index, retries + 1);
      }, 300);
    } else {
      log('info', 'Port ' + attemptPort + ' unavailable (' + err.code + '), trying next port...');
      setTimeout(function() {
        tryPort(ports, index + 1, 0);
      }, 200);
    }
  };

  var listeningHandler = function() {
    listenServer.removeListener('error', errorHandler);
    server = listenServer;
    port = attemptPort;
    log('info', 'Listening on port ' + port);
    
    var addr = listenServer.address();
    log('debug', '[LISTEN] Bound to ' + addr.address + ':' + addr.port);
    
    var uptime = ((Date.now() - _startTime) / 1000).toFixed(1);
    log('info', '[LISTEN] Server ready in ' + uptime + 's on https://0.0.0.0:' + port);
    
    // Start HTTP redirect server safely after HTTPS server is bound
    startHttpRedirectServer(port);
  };

  listenServer.once('error', errorHandler);
  listenServer.once('listening', listeningHandler);

  log('debug', '[PORT] Attempting to bind HTTPS on port ' + attemptPort + ' (attempt ' + (retries + 1) + ')...');
  try {
    listenServer.listen(attemptPort, '0.0.0.0');
  } catch(e) {
    errorHandler(e);
  }
};

var isShuttingDown = false;
function gracefulShutdown(signal) {
  if (isShuttingDown) return;
  isShuttingDown = true;
  console.log('[NODE] Gracefully closing server sockets and cleaning up on signal ' + signal + '...');

  if (activeRedirectServer && activeRedirectServer.close) {
    try { activeRedirectServer.close(); } catch(e) {}
  }

  try {
    if (gp_hub && gp_hub.cleanUp) gp_hub.cleanUp();
    if (kb_hub && kb_hub.cleanUp) kb_hub.cleanUp();
    if (tp_hub && tp_hub.cleanUp) tp_hub.cleanUp();
    if (wh_hub && wh_hub.cleanUp) wh_hub.cleanUp();
  } catch(e) {}

  if (server && server.close) {
    server.close(function() {
      console.log('[NODE] HTTPS server socket closed successfully.');
      process.exit(0);
    });
    setTimeout(function() {
      process.exit(0);
    }, 400);
  } else {
    process.exit(0);
  }
}

// Start trying ports
tryPort(allPorts, 0, 0);

}).call(this);
