// Generated by CoffeeScript 2.7.0
(function() {
  /*
  Virtual touchpad hub class
  */
  var config, log, num_touchpads, touchpad, virtual_touchpad_hub;

  touchpad = require('./virtual_touchpad');

  log = require('../lib/log');

  config = require('../config');

  num_touchpads = config.maxTouchpads || 4;

  virtual_touchpad_hub = class virtual_touchpad_hub {
    constructor() {
      this.touchpads = [];
    }

    connectTouchpad(callback) {
      var touchpadId = -1;
      // Search for a free (disconnected) slot first
      for (var i = 0; i < this.touchpads.length; i++) {
        if (this.touchpads[i] === undefined || this.touchpads[i] === void 0) {
          touchpadId = i;
          break;
        }
      }
      // If no free slot, try to append
      if (touchpadId === -1) {
        touchpadId = this.touchpads.length;
      }
      // Check if max touchpads reached
      if (touchpadId >= num_touchpads) {
        log('warning', "Couldn't add new touchpad: no slot left.");
        callback(-1);
        return;
      }
      // Create and connect the touchpad
      log('info', 'Creating and connecting to touchpad number ' + touchpadId);
      this.touchpads[touchpadId] = new touchpad();
      return this.touchpads[touchpadId].connect(function() {
        return callback(touchpadId);
      }, function(err) {
        log('error', "Couldn't connect to touchpad:\n" + JSON.stringify(err));
        return callback(-1);
      });
    }

    disconnectTouchpad(touchpadId, callback) {
      if (this.touchpads[touchpadId]) {
        return this.touchpads[touchpadId].disconnect(() => {
          this.touchpads[touchpadId] = void 0;
          return callback();
        });
      }
    }

    sendEvent(touchpadId, event) {
      if (this.touchpads[touchpadId]) {
        return this.touchpads[touchpadId].sendEvent(event);
      }
    }

    getStatus() {
      var slots = [];
      var used = 0;
      for (var i = 0; i < num_touchpads; i++) {
        var occupied = !!this.touchpads[i];
        slots.push(occupied);
        if (occupied) used++;
      }
      return {
        slots: slots,
        total: num_touchpads,
        used: used,
        free: num_touchpads - used
      };
    }

  };

  module.exports = virtual_touchpad_hub;

}).call(this);
